### ISSUE TITLE
[FEATURE] 공감 개수 조회 기능

### ISSUE THREAD

**Issue by senzoo-oh** [cloud-sobeelog/emoticon#1]
## 💼 TASK 개요 
캘린더에서 요청하는 공감개수 조회 기능

## ✅ TODO 및 진행현황 

- [ ] getCountOfEmoticon 컨트롤러 추가
- [ ] getCountOfEmoticon SQL문 추가
- [ ] 라우터 인덱스 변경
